export default {
  settings: {
    keycode: '',
    user: 'Unknown',
    isIncludeCollision: true,
    isIncludeBearing: true,
    isIncludeCourse: true,
    isIncludeAltitude: true,
    gpsUpdatesPerMinute: 1,
    maxDistance: 1,
    maxLag: 1,
    minSpeed: 1,
    maxContacts: 1,
    speechVoice: 1,
    speechRate: 1,
    speechPitch: 1,
  },
  coords: {
    latitude: 1,
    longitude: 2,
    altitude: 3,
    speed: 4,
    heading: 5,
    accuracy: 6,
    altitudeAccuracy: 7,
    timestamp: 8,
  },
  still_speaking: false,
  next_thing_to_say: '',
  apidata: {},
  availableVoices: [],
}

